[tasks.ci]
workspace = false
run_task = { name = "ci-flow", fork = true }

[tasks.readme]
workspace = false
command = "cargo"
args = ["readme", "--input", "src/lib.rs", "--template", "${PWD}/README.tpl", "--output", "${PWD}/README.md"]

[tasks.t]
workspace = false
run_task = { name = "test", fork = true }

[tasks.r]
workspace = false
run_task = "readme"

[tasks.outdated]
args = ["outdated", "--root-deps-only", "--exit-code", "0"]
